name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # كل يوم
  workflow_dispatch: # يسمحلك تشغله يدويًا
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: SobihMohamed
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
